function [g,esup,dvr,edisc] = GravPrismaCuadrado(prismas,puntos,algoritmo,pe,tmax)
%*******************************************************************************
% GRAVPRISMACUADRADO
%
% Purpose:
%   Computes the gravitational attraction generated by a set of square-based
%   rectangular prisms at a set of observation points.
%
% Syntax:
%   [g, esup, dvr, edisc] = GravPrismaCuadrado(prismas, puntos, algoritmo, pe, tmax)
%
% Inputs:
%   prismas   - Matrix defining the prism models. Each row represents one
%               prism through its center coordinates, geometric dimensions,
%               orientation angles, and density.
%   puntos    - Matrix containing the coordinates of the observation points.
%   algoritmo - Algorithm-selection parameter.
%   pe        - Discretization parameter passed to the prism-discretization
%               routine.
%   tmax      - Optional execution-time parameter retained for compatibility.
%
% Outputs:
%   g         - Gravitational-attraction components at the observation points.
%   esup      - Cell array reserved for prism-surface information.
%   dvr       - Vector reserved for discretization information.
%   edisc     - Cell array containing the transformed prism vertices.
%
% Dependencies:
%   DiscretizaPrisma.m
%   GravNubePuntos.m
%
% Authors:
%   GPINV Research Group
%   University of Oviedo, Spain
%
% Copyright (c) 2026 GPINV Research Group, University of Oviedo
%
% This repository version preserves the computational logic used in the
% associated gravity-inversion experiments.
%*******************************************************************************

% Set default input values
if nargin < 2
    error('Número incorrecto de argumentos de entrada');
elseif nargin == 2
    algoritmo = 0;
    pe = 1.0;
    tmax = 0.0;
elseif nargin == 3
    pe = 1.0;
    tmax = 0.0;
elseif nargin == 4
    tmax = 0.0;
end

[nPris,~] = size(prismas);
[nP,~] = size(puntos);

g = zeros(nP,3);
esup = cell(nPris,1);
dvr = zeros(nPris,1);
edisc = cell(nPris,1);

G = 6.67430e-11;

for i=1:nPris

    %-----------------------------------------
    % Prism parameters.
    %-----------------------------------------
    xc = prismas(i,1);
    yc = prismas(i,2);
    zc = prismas(i,3);
    a  = prismas(i,4);
    b  = prismas(i,5);
    acim = prismas(i,6);
    inc  = prismas(i,7);
    rho  = prismas(i,8);

    %-----------------------------------------
    % Rotation matrix
    %-----------------------------------------
    Rx = [1 0 0;
          0 cos(inc) -sin(inc);
          0 sin(inc) cos(inc)];

    Rz = [cos(acim) -sin(acim) 0;
          sin(acim)  cos(acim) 0;
          0 0 1];

    R = Rz * Rx;

    [X,Y,Z] = meshgrid([-a a],[-a a],[-b b]);
   aux = [X(:) Y(:) Z(:)];
   aux = (R * aux')';
aux = aux + [xc yc zc];
edisc{i} = aux;
    

[vox,dvol] = DiscretizaPrisma(a,b,pe);

n = size(vox,1);
m = rho * dvol;

% Rotate discretized prism coordinates 
vox_rot = (R * vox')';

% Translate coordinates to the global reference system.
vox_global = vox_rot + [xc yc zc];

vox_global = [vox_global m*ones(n,1)];

atrac = GravNubePuntos(vox_global, puntos);

g = g + atrac;
end

